
load('/projects/sst_noaa/daily_output/noaa_hiRes_sst.mat')
load('/projects/sst_noaa/geo_noaa_hiRes_sst.mat')
%%
[overlay_table,overlay_table_cumsum,tbl] = timetable2overlaystructure(SST)
%%
set(0,'defaultfigurepaperunits','centimeters');
set(0,'DefaultAxesFontSize',16)
set(0,'defaultfigurecolor','w');
set(0,'defaultfigureinverthardcopy','off');
set(0,'defaultfigurepaperorientation','landscape');
set(0,'defaultfigurepapersize',[35 21]);
set(0,'defaultfigurepaperposition',[.25 .25 [35 21]-0.5]);
set(0,'DefaultTextInterpreter','none');
set(0, 'DefaultFigureUnits', 'centimeters');
set(0, 'DefaultFigurePosition', [.25 .25 [35 21]-0.5]);

%% Frávik mánðarmeðaltala
clines = lines(5)
figure, hold on
% sst_S
plot(SSTMA.Time,SSTMA.sst_S,'color',[clines(1,:),0.3],...
    'DisplayName','SST-S')
h1 = plot(SSTMA.Time,movmean(SSTMA.sst_S,10),'color',clines(1,:),...
    'LineWidth',2,'DisplayName','SST-S')
% sst_N
plot(SSTMA.Time,SSTMA.sst_N,'color',[clines(2,:),0.3],...
    'DisplayName','SST-N')
h2 = plot(SSTMA.Time,movmean(SSTMA.sst_N,10),...
    'LineWidth',2,'color',clines(2,:),'DisplayName','SST-N')
% sst_W
plot(SSTMA.Time,SSTMA.sst_W,'color',[clines(3,:),0.3],...
    'DisplayName','SST-W')
h3 = plot(SSTMA.Time,movmean(SSTMA.sst_W,10),...
    'LineWidth',2,'color',clines(3,:),'DisplayName','SST-W')
% sst_W
plot(SSTMA.Time,SSTMA.sst_E,'color',[clines(4,:),0.3],...
    'DisplayName','SST-E')
h4 = plot(SSTMA.Time,movmean(SSTMA.sst_E,10),...
    'LineWidth',2,'color',clines(4,:),'DisplayName','SST-E')
% sst_cold_blob
plot(SSTMA.Time,SSTMA.sst_cold_blob,'color',[clines(5,:),0.3],...
    'DisplayName','NAWH')
h5 = plot(SSTMA.Time,movmean(SSTMA.sst_cold_blob,10),...
    'LineWidth',2,'color',clines(5,:),'DisplayName','NAWH')

ylabel('SST monthly anomanly (°C)')
hline(0)
grid on
grid minor
legend([h1,h2,h3,h4,h5],'Location','southoutside','NumColumns',5)
% Merkingar
text(0.01,0.96,['Nýjustu gögn: ',datestr(SST.Time(end))],...
    'Units','normalized','HorizontalAlignment','left',...
    'VerticalAlignment','bottom','FontSize',12,'FontWeight','bold',...
    'Interpreter','none');

text(0.01,0.93,['Uppfært: ',datestr(now,'dd.mm.yyyy')],...
    'Units','normalized','HorizontalAlignment','left',...
    'VerticalAlignment','bottom','FontSize',12,'FontWeight','bold',...
    'Interpreter','none');

text(0.01,0.9,['Gögn: SST-NOAA-OISST.v2.highres'],...
    'Units','normalized','HorizontalAlignment','left',...
    'VerticalAlignment','bottom','FontSize',12,'FontWeight','bold',...
    'Interpreter','none');
title('Sjávarhiti á reitum við Ísland - Hlaupandi frávik mánaða (10 mo)')

ax = gca;
xtickangle(45);
%set(gca,'TickDir','out');
set(gca, ...
    'Box'         , 'off'     , ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.02 .02] , ...
    'XMinorTick'  , 'on'      , ...
    'YMinorTick'  , 'on'      , ...
    'YGrid'       , 'on'      , ...
    'XColor'      , [.3 .3 .3], ...
    'YColor'      , [.3 .3 .3], ...
    'LineWidth'   , 1         );
%% save data to image folder
cd '/projects/sst_noaa/daily_output'
exportgraphics(gcf,'SSTMA_daily.jpg');
exportgraphics(gcf,'SSTMA_10month_movmean_daily.pdf');

%% Dagsmeðaltöl
clines = lines(5)
figure, hold on
% sst_S
plot(SST.Time,SST.sst_S,'color',[clines(1,:),0.3],...
    'DisplayName','SST-S')
h1 = plot(SST.Time,movmean(SST.sst_S,10),'color',clines(1,:),...
    'LineWidth',2,'DisplayName','SST-S')
% sst_N
plot(SST.Time,SST.sst_N,'color',[clines(2,:),0.3],...
    'DisplayName','SST-N')
h2 = plot(SST.Time,movmean(SST.sst_N,10),...
    'LineWidth',2,'color',clines(2,:),'DisplayName','SST-N')
% sst_W
plot(SST.Time,SST.sst_W,'color',[clines(3,:),0.3],...
    'DisplayName','SST-W')
h3 = plot(SST.Time,movmean(SST.sst_W,10),...
    'LineWidth',2,'color',clines(3,:),'DisplayName','SST-W')
% sst_W
plot(SST.Time,SST.sst_E,'color',[clines(4,:),0.3],...
    'DisplayName','SST-E')
h4 = plot(SST.Time,movmean(SST.sst_E,10),...
    'LineWidth',2,'color',clines(4,:),'DisplayName','SST-E')
% sst_cold_blob
plot(SST.Time,SST.sst_cold_blob,'color',[clines(5,:),0.3],...
    'DisplayName','NAWH')
h5 = plot(SST.Time,movmean(SST.sst_cold_blob,10),...
    'LineWidth',2,'color',clines(5,:),'DisplayName','NAWH')

ylabel('SST (°C)')
grid on
grid minor
legend([h1,h2,h3,h4,h5],'Location','southoutside','NumColumns',5)

% Merkingar
text(0.01,0.96,['Nýjustu gögn: ',datestr(SST.Time(end))],...
    'Units','normalized','HorizontalAlignment','left',...
    'VerticalAlignment','bottom','FontSize',12,'FontWeight','bold',...
    'Interpreter','none');

text(0.01,0.93,['Uppfært: ',datestr(now,'dd.mm.yyyy')],...
    'Units','normalized','HorizontalAlignment','left',...
    'VerticalAlignment','bottom','FontSize',12,'FontWeight','bold',...
    'Interpreter','none');

text(0.01,0.9,['Gögn: SST-NOAA-OISST.v2.highres'],...
    'Units','normalized','HorizontalAlignment','left',...
    'VerticalAlignment','bottom','FontSize',12,'FontWeight','bold',...
    'Interpreter','none');

title('Sjávarhiti á reitum við Ísland - dagsmeðaltöl')

ax = gca;
xtickangle(45);
%set(gca,'TickDir','out');
set(gca, ...
    'Box'         , 'off'     , ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.02 .02] , ...
    'XMinorTick'  , 'on'      , ...
    'YMinorTick'  , 'on'      , ...
    'YGrid'       , 'on'      , ...
    'XColor'      , [.3 .3 .3], ...
    'YColor'      , [.3 .3 .3], ...
    'LineWidth'   , 1         );
%% save data to image folder
cd '/projects/sst_noaa/daily_output'
exportgraphics(gcf,'SST_daily_all_time.jpg');
exportgraphics(gcf,'SST_daily_all_time.pdf');
%%
clines = lines(5)
figure, hold on
% sst_S
plot(SST.Time,SST.sst_S,'color',[clines(1,:),0.3],...
    'DisplayName','SST-S')
h1 = plot(SST.Time,movmean(SST.sst_S,10),'color',clines(1,:),...
    'LineWidth',2,'DisplayName','SST-S')
% sst_N
plot(SST.Time,SST.sst_N,'color',[clines(2,:),0.3],...
    'DisplayName','SST-N')
h2 = plot(SST.Time,movmean(SST.sst_N,10),...
    'LineWidth',2,'color',clines(2,:),'DisplayName','SST-N')
% sst_W
plot(SST.Time,SST.sst_W,'color',[clines(3,:),0.3],...
    'DisplayName','SST-W')
h3 = plot(SST.Time,movmean(SST.sst_W,10),...
    'LineWidth',2,'color',clines(3,:),'DisplayName','SST-W')
% sst_W
plot(SST.Time,SST.sst_E,'color',[clines(4,:),0.3],...
    'DisplayName','SST-E')
h4 = plot(SST.Time,movmean(SST.sst_E,10),...
    'LineWidth',2,'color',clines(4,:),'DisplayName','SST-E')
% sst_cold_blob
plot(SST.Time,SST.sst_cold_blob,'color',[clines(5,:),0.3],...
    'DisplayName','NAWH')
h5 = plot(SST.Time,movmean(SST.sst_cold_blob,10),...
    'LineWidth',2,'color',clines(5,:),'DisplayName','NAWH')

ylabel('SST (°C)')
grid on
grid minor
legend([h1,h2,h3,h4,h5],'Location','southoutside','NumColumns',5)

% Merkingar
text(0.01,0.96,['Nýjustu gögn: ',datestr(SST.Time(end))],...
    'Units','normalized','HorizontalAlignment','left',...
    'VerticalAlignment','bottom','FontSize',12,'FontWeight','bold',...
    'Interpreter','none');

text(0.01,0.93,['Uppfært: ',datestr(now,'dd.mm.yyyy')],...
    'Units','normalized','HorizontalAlignment','left',...
    'VerticalAlignment','bottom','FontSize',12,'FontWeight','bold',...
    'Interpreter','none');

text(0.01,0.9,['Gögn: SST-NOAA-OISST.v2.highres'],...
    'Units','normalized','HorizontalAlignment','left',...
    'VerticalAlignment','bottom','FontSize',12,'FontWeight','bold',...
    'Interpreter','none');

title('Sjávarhiti á reitum við Ísland - dagsmeðaltöl')

ax = gca;
xtickangle(45);
%set(gca,'TickDir','out');
set(gca, ...
    'Box'         , 'off'     , ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.02 .02] , ...
    'XMinorTick'  , 'on'      , ...
    'YMinorTick'  , 'on'      , ...
    'YGrid'       , 'on'      , ...
    'XColor'      , [.3 .3 .3], ...
    'YColor'      , [.3 .3 .3], ...
    'LineWidth'   , 1         );

xlim([datetime('now')-calmonths(6),datetime('now')])
%% save data to image folder
cd '/projects/sst_noaa/daily_output'
exportgraphics(gcf,'SST_daily_6mo.jpg');
exportgraphics(gcf,'SST_daily_6mo.pdf');
%% Overlay plotting

fnames = fieldnames(overlay_table);
%%
for i = 1:length(fnames)
    figure, hold on

    fname = fnames(i);
    years2plot = [2021,2022,2023]
        switch string(fname)
            case 'sst_isl'
                fig_title = 'Sjávarhiti - Ísland [70 60],[-10 -30]';
            case 'sst_S'
                fig_title = 'Sjávarhiti - Ísland - Suður [[65 60],[-20 -30]';
            case 'sst_N'
                fig_title = 'Sjávarhiti - Ísland - Norður [70 65],[-10 -20]';
            case 'sst_W'
                fig_title = 'Sjávarhiti - Ísland - Vestur [70 65],[-20 -30]';
            case 'sst_E'
                fig_title = 'Sjávarhiti - Ísland - Austur [65 60],[-10 -20]';
            case 'sst_cold_blob'
                fig_title = 'Sjávarhiti - Ísland - Kaldur blettur [56 50],[-33 -39]';
        end

    unit = '°C';
    ylabel_name = 'Sjávarhiti';
    text_lower_right = 'Gögn: SST-NOAA-OISST.v2.highres';

    plt_overlay(overlay_table.(string(fname)),tbl.(string(fname)),...
        years2plot,fig_title,unit,...
        ylabel_name,text_lower_right)

%% save data to image folder
    cd '/projects/sst_noaa/daily_output'
    exportgraphics(gcf,['SST_overlay_',char(fname),'.jpg']);
    exportgraphics(gcf,['SST_overlay_',char(fname),'.pdf']);
end

%% Plot maps


